name: warteg-bot
services:
  - name: worker
    type: worker
    git:
      branch: main
    build:
      buildpack:
        build_command: pip install -r requirements.txt
    run:
      command: python bot.py
    env:
      - key: TELEGRAM_TOKEN
        value: ""
      - key: GEMINI_API_KEY
        value: ""
      - key: APPS_SCRIPT_URL
        value: ""
